### PR TITLE
Fix query items comparison

### LINKED ISSUE #85: Order of query parameters should not matter
If the same query parameters are used but in a different order, the recording is not found. Query parameters order should not affect request matching.

### PR DESCRIPTION
**Pull request by ilyapuchka**
Resolves #85 
One case when comparing just names is insufficient is when names are equal. In this case, sorting will be unstable and can result if false negative matching results.

### CODE REVIEW

File: Vinyl/Extensions/URLQueryItem.swift [hunk 1]
```diff
@@ -11,6 +11,11 @@ import Foundation
 extension URLQueryItem: Comparable {
     
     public static func < (lhs: URLQueryItem, rhs: URLQueryItem) -> Bool {
-        return lhs.name < rhs.name
+        guard lhs.name < rhs.name else { return false }
+        switch (lhs.value, rhs.value) {
+        case let (lhs?, rhs?): return lhs < rhs
+        case (nil, nil): return true
```
Comment (ilyapuchka) [inline Vinyl/Extensions/URLQueryItem.swift]: should never happen ™

File: Vinyl/Extensions/URLQueryItem.swift [hunk 2]
```diff
@@ -11,6 +11,11 @@ import Foundation
 extension URLQueryItem: Comparable {
     
     public static func < (lhs: URLQueryItem, rhs: URLQueryItem) -> Bool {
-        return lhs.name < rhs.name
+        guard lhs.name < rhs.name else { return false }
+        switch (lhs.value, rhs.value) {
+        case let (lhs?, rhs?): return lhs < rhs
+        case (nil, nil): return false
```
Comment (ilyapuchka) [inline Vinyl/Extensions/URLQueryItem.swift]: should never happen ™
